# Generated by Django 4.1.7 on 2023-04-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='default_product_image.jpg', upload_to='product'),
        ),
    ]
