# Generated by Django 4.1.7 on 2023-04-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('AP', 'All Products'), ('NA', 'New Arrivals'), ('TS', 'T Shirts'), ('HS', 'Hoodies'), ('SS', 'Sweet Shirts')], default='AP', max_length=2),
        ),
    ]
