# Generated by Django 4.1.7 on 2023-04-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('AP', 'All Products'), ('NA', 'New Arrivals'), ('TS', 'T Shirts'), ('HS', 'Hoodies'), ('SS', 'Sweet Shirts')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='product'),
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
