# Generated by Django 4.1.7 on 2023-04-28 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_product_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
    ]
