# Generated by Django 4.1.7 on 2023-05-08 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
