# Generated by Django 4.1.7 on 2023-05-10 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_product_avg_rating_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='avg_rating',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
