# Generated by Django 4.1.7 on 2023-05-11 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
