# Generated by Django 4.1.7 on 2023-05-18 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_customer_mobile_productvariant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
