# Generated by Django 4.1.7 on 2023-06-02 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_size_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='size',
            name='name',
        ),
        migrations.AddField(
            model_name='size',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='app.product'),
        ),
        migrations.AddField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
