# Generated by Django 4.1.7 on 2023-06-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_remove_product_sizes_remove_size_name_size_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(default='S', max_length=10),
        ),
    ]
