# Generated by Django 4.1.7 on 2023-06-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_alter_cart_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.CharField(default='S', max_length=10),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(default='S', max_length=10),
        ),
    ]
