# Generated by Django 4.1.7 on 2023-06-07 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_alter_cart_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.size'),
        ),
    ]
