# Generated by Django 4.1.7 on 2023-06-07 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_orderplaced_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='size',
        ),
    ]
