# Generated by Django 4.1.7 on 2023-06-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_remove_product_size_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(default='S', max_length=10),
        ),
    ]
