# Generated by Django 4.1.7 on 2023-06-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_cart_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
