# Generated by Django 4.1.7 on 2023-06-27 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='size',
            name='stock',
        ),
    ]
